/**
 * Generate static books for storybook from the mock-rgs math module.
 *
 *   pnpm --filter=olympus gen-books
 *
 * Output:
 *   apps/olympus/src/stories/data/base_books.ts
 *   apps/olympus/src/stories/data/bonus_books.ts
 *
 * Re-run any time the math changes; commit the generated files so storybook
 * stays in sync with the latest reel composition / paytable.
 *
 * Each generated file exports `default` an array of round objects with the
 * shape expected by `MODE_<MODE>/book/random` stories (matches lines/scatter
 * sample apps).
 */

import { writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

import {
  runBaseSpin,
  runBonusBuy,
  createSeededRng,
} from '../mock-rgs/math/index.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const OUT_DIR = path.join(__dirname, '..', 'src', 'stories', 'data');

const BASE_BOOK_COUNT = 50;
const BONUS_BOOK_COUNT = 25;
const SEED = 0xc0ffee;

const buildBook = (id, mode, rng) => {
  const round = mode === 'BONUS'
    ? runBonusBuy({ betAmount: 1, rng })
    : runBaseSpin({ betAmount: 1, rng });
  return {
    id,
    payoutMultiplier: Number(round.totalWin.toFixed(6)),
    events: round.bookEvents,
    criteria: mode === 'BONUS' ? 'bonus' : '0',
    baseGameWins: 0,
    freeGameWins: 0,
  };
};

const serialize = (data) =>
  `// AUTO-GENERATED by scripts/gen-books.mjs — do not edit by hand.\n` +
  `// Re-generate with: pnpm --filter=olympus gen-books\n\n` +
  `export default ${JSON.stringify(data, null, 2)} as const;\n`;

const main = () => {
  mkdirSync(OUT_DIR, { recursive: true });
  const rng = createSeededRng(SEED);

  const base = [];
  for (let i = 1; i <= BASE_BOOK_COUNT; i++) base.push(buildBook(i, 'BASE', rng));
  writeFileSync(path.join(OUT_DIR, 'base_books.ts'), serialize(base));
  console.log('[gen-books] wrote %d base books', base.length);

  const bonus = [];
  for (let i = 1; i <= BONUS_BOOK_COUNT; i++) bonus.push(buildBook(i, 'BONUS', rng));
  writeFileSync(path.join(OUT_DIR, 'bonus_books.ts'), serialize(bonus));
  console.log('[gen-books] wrote %d bonus books', bonus.length);
};

main();
